import logging

from app.schemas.review import (
    Category,
    ReviewFinding,
    ReviewTaskRequest,
    ReviewTaskResult,
    Severity,
)

logger = logging.getLogger("codesentinel-ai.review_service")


class ReviewService:
    """Phase 5.1 mock review service.

    Generates a deterministic ReviewTaskResult with one mock finding.
    Real LLM analysis will be introduced in Phase 5.2+.
    """

    def review(self, request: ReviewTaskRequest) -> ReviewTaskResult:
        logger.info(
            "Reviewing task %d: repository=%s, pr=%d, sha=%s",
            request.task_id,
            request.repository,
            request.pr_number,
            request.commit_sha,
        )

        finding = self._mock_finding(request)

        result = ReviewTaskResult(
            task_id=request.task_id,
            status="COMPLETED",
            report={
                "summary": "Mock review completed for "
                f"{request.repository}#{request.pr_number}.",
                "total_findings": 1,
            },
            findings=[finding],
        )

        logger.info(
            "Review completed for task %d: status=%s, findings=%d",
            result.task_id,
            result.status,
            len(result.findings),
        )
        return result

    def _mock_finding(self, request: ReviewTaskRequest) -> ReviewFinding:
        file_path = request.files[0] if request.files else "mock/Example.java"
        return ReviewFinding(
            category=Category.QUALITY,
            severity=Severity.LOW,
            confidence=0.5,
            rule_id="MOCK-001",
            title="Mock review finding",
            file_path=file_path,
            start_line=1,
            end_line=1,
            description="Mock finding generated by the Phase 5.1 review service.",
            reason="Deterministic placeholder finding used to verify the "
            "HTTP boundary between the worker and the AI service.",
            suggestion="No action required. Real analysis replaces this "
            "finding in Phase 5.2.",
            references=["MOCK"],
        )
